openapi: "3.0.3"
info:
  title: RulesKit API (Engraving Rules)
  version: 0.2.0
paths:
  $ref: ./openapi/rules-as-functions.yaml#/paths
components:
  $ref: ./openapi/rules-as-functions.yaml#/components
