openapi: 3.1.0
info:
  $ref: ./openapi/rules-as-functions.yaml#/info
servers:
  $ref: ./openapi/rules-as-functions.yaml#/servers
paths:
  $ref: ./openapi/rules-as-functions.yaml#/paths
components:
  $ref: ./openapi/rules-as-functions.yaml#/components
