openapi: 3.1.0
info:
  title: RulesKit API (Engraving Rules)
  version: 0.2.0
  description: Typed OpenAPI for Engraving rules; sections reference the typed spec.
servers: []
paths:
  $ref: ./openapi/rules-as-functions.yaml#/paths
components:
  $ref: ./openapi/rules-as-functions.yaml#/components
